### ISSUE TITLE
where is the dataset

### ISSUE THREAD

**Issue by SeekPoint** [bojone/bert_in_keras#2]

**Comment by bojone** [comment]
文章（ https://kexue.fm/archives/6736 ）已经给出所有的数据来源，请认真阅读，不要浪费大家时间～

情感分类的标注数据在这里：https://kexue.fm/archives/3414
事件主体抽取比赛还没结束，报个名就能下载：https://biendata.com/competition/ccks_2019_4
至于关系抽取的比赛已经结束，之前没下载到我也没办法，据说百度迟点会将它公开发布。
