### ISSUE TITLE
不好意思 作者  能不能问一下数据的格式是怎么样的  

### ISSUE THREAD

**Issue by kedimomo** [bojone/bert_in_keras#3]
苏大  能不能给个数据例子出来  就一个就行    好像关系抽取  relation_extract.py 那个 前面两个 将多行json塞进数组能理解  
但是这句就不懂了 
id2predicate, predicate2id = json.load(open('../datasets/all_50_schemas_me.json'))
原本的数据是 
{"object_type": "地点", "predicate": "祖籍", "subject_type": "人物"}
{"object_type": "人物", "predicate": "父亲", "subject_type": "人物"}

怎么处理呢  谢谢

**Comment by kedimomo** [comment]
给一个数据的模板  不会被人说侵权的     不表现出数据就好了  这样也方便  造自己的数据

**Comment by ZihaoGENG** [comment]
> 给一个数据的模板 不会被人说侵权的 不表现出数据就好了 这样也方便 造自己的数据

搜一下百度2019信息抽取，又不是搜不到

**Comment by kedimomo** [comment]
@ZihaoGENG     谢谢回复   上面的格式就是找到的all_50_schemas  源数据格式     现在想知道  all_50_schemas_me.json  里面的格式是怎么样的   因为直接用原始数据不行的   作者转换过一次   如果你知道  麻烦告诉我一下  谢谢

**Comment by bojone** [comment]
https://github.com/bojone/kg-2019/blob/master/data_trans.py
通过这个脚本转换原始数据的。

bert关系抽取本身是作为之前dgcnn那篇的后续，可能你没看之前那篇，所以不知道来龙去脉。

**Comment by kedimomo** [comment]
@bojone   万分感谢   这几天都在思考这个问题
