### ISSUE TITLE
验证集loss降不下去怎么办

### ISSUE THREAD

**Issue by hc944822354** [bojone/bert_in_keras#5]
![Snipaste_2019-06-21_10-38-11](https://user-images.githubusercontent.com/16319068/59893871-00c86a00-9411-11e9-87e0-1e0e10e87a9a.png)
验证集loss降不下去怎么办

**Comment by bojone** [comment]
你自己的数据集？还是本文三个例子的数据集？

**Comment by hc944822354** [comment]
> 你自己的数据集？还是本文三个例子的数据集？

用的情感分析的代码，用的也是你一样的数据集

**Comment by wan560** [comment]
我也是一样的问题，为什么验证集准确率能到95%+，我一直50%+。一样的代码和数据

**Comment by hc944822354** [comment]
> 我也是一样的问题，为什么验证集准确率能到95%+，我一直50%+。一样的代码和数据

我解决了，训练集要随机

**Comment by wan560** [comment]
> 
> 
> > 我也是一样的问题，为什么验证集准确率能到95%+，我一直50%+。一样的代码和数据
> 
> 我解决了，训练集要随机

具体是改哪呢？我看已经suffle过整个数据了，代码58行：np.random.shuffle(list(random_order))

**Comment by hc944822354** [comment]
> > > 我也是一样的问题，为什么验证集准确率能到95%+，我一直50%+。一样的代码和数据
> > 
> > 
> > 我解决了，训练集要随机
> 
> 具体是改哪呢？我看已经suffle过整个数据了，代码58行：np.random.shuffle(list(random_order))

我之前是博主源代码shuffle代码在py3上有点问题，你验证下是不是真的shuffle了，如果真的shuffle了我也不知道什么原因，我是改了之后就没问题了
改完代码如下：
按照9:1的比例划分训练集和验证集
random_order = list(range(len(data)))
np.random.shuffle(random_order)

train_data = [data[j] for i, j in enumerate(random_order) if i % 10 != 0]
valid_data = [data[j] for i, j in enumerate(random_order) if i % 10 == 0]

**Comment by wan560** [comment]
> random_order

好的，我再试试看，谢谢~
