### ISSUE TITLE
如何对bert微调后的模型进行加载？

### ISSUE THREAD

**Issue by wangxing9315** [bojone/bert_in_keras#7]
您好!在参考了您的代码后，想问一下后续一点的问题
在对bert进行微调过后用 model.save()保存了模型。
但是在加载模型的时候发生了报错：
ValueError: Unknown layer: TokenEmbedding
加载方式：model = load_model(self.fmodel, custom_objects={"tf":tf, "backend":backend})
这个问题该怎么解决？

**Comment by acacess** [comment]
@wangxing9315: 正好摸索了一下，需要参考 keras-bert 的代码：

`from keras.models import load_model`
`from keras_bert.layers import TokenEmbedding`
`from keras_pos_embd import PositionEmbedding`
`from keras_layer_normalization import LayerNormalization`
`from keras_multi_head import MultiHeadAttention`
`from keras_position_wise_feed_forward import FeedForward`
`from keras_transformer import gelu`

`CUSTOM_OBJECTS={'TokenEmbedding':TokenEmbedding, `
              `'PositionEmbedding': PositionEmbedding,`
              `'LayerNormalization': LayerNormalization,`
              `'MultiHeadAttention': MultiHeadAttention,`
              `'FeedForward': FeedForward,`
              `'gelu': gelu}`

`load_model(MODEL_OUTPUT, CUSTOM_OBJECTS)`

**Comment by wangxing9315** [comment]
非常感谢大佬，刚好我也看到了！

然后在实际中采用了这种方式
from keras_bert import get_custom_objects

bert_custom = get_custom_objects()
custom_objects = {"tf": tf, "backend": backend}
custom_objects.update(bert_custom)
model = load_model(self.fmodel, custom_objects=custom_objects)

**Comment by bojone** [comment]
我脚本里边有说过用model.save()来保存模型吗？我脚本里边从来都是model.save_weights()的...

用model.save()就是一个偷懒的作死的选择～
